-- BlackNode-Flow (Hyprland Lua)
-- ----------------------------------------

hl.curve("fluid", { type = "bezier", points = { {0.76, 0}, {0.24, 1} } })
hl.curve("snappy", { type = "bezier", points = { {0.33, 1}, {0.68, 1} } })
hl.curve("overshot", { type = "bezier", points = { {0.13, 0.99}, {0.29, 1.1} } })

hl.animation({ leaf = "windows", enabled = true, speed = 4, curve = "overshot", style = "slide" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4, curve = "overshot", style = "slide left" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 4, curve = "fluid", style = "slide right" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, curve = "overshot", style = "slide" })

hl.animation({ leaf = "fadeIn", enabled = true, speed = 5, curve = "fluid" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 5, curve = "fluid" })

hl.animation({ leaf = "workspaces", enabled = true, speed = 6, curve = "fluid", style = "slide" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 6, curve = "fluid", style = "slide" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 6, curve = "fluid", style = "slide" })

hl.animation({ leaf = "layers", enabled = true, speed = 5, curve = "snappy", style = "slide" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 5, curve = "snappy", style = "slide" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 5, curve = "fluid", style = "slide" })